In [1]:
# Import dependencies
import pandas as pd

In [107]:
# Clean QBs
xl1 = pd.read_csv('data_raw/weekly_qb.csv')

xl1 = xl1.drop(columns=['Unnamed: 0', 'Unnamed: 2_level_0_Pts*'])

xl1 = xl1.rename(columns={'Unnamed: 0_level_0_Player':'player', 'Unnamed: 1_level_0_Game':'opponent',
       'Passing_Att':'passA', 'Passing_Cmp':"passC", 'Passing_Yds':"passY",
       'Passing_TD':'passT', 'Passing_Int':'passI', 'Passing_2Pt':'pass2', 'Rushing_Att':'rushA',
       'Rushing_Yds':'rushY', 'Rushing_TD':'rushT', 'Rushing_2Pt':'rush2', 'Receiving_Rec':'recC',
       'Receiving_Yds':'recY', 'Receiving_TD':'recT', 'Receiving_2Pt':'rec2', 'Fumbles_FL':'fum', 'Fumbles_TD':'fumT'
       })
xl1 = xl1[['player', 'season', 'week', 'team', 'opponent', 'passA', 'passC', 'passY', 'passT', 'passI', 'pass2',
       'rushA', 'rushY', 'rushT', 'rush2', 'recC', 'recY', 'recT', 'rec2',
       'fum']]
xl1[['tm1', 'tm2']] = xl1['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl1['opponent'] = xl1.apply(teamPicker, axis=1)

xl1 = xl1.drop(columns=['tm1', 'tm2'])

xl1[['player', 'todrop']] = xl1['player'].str.split('.\xa0', expand=True)
xl1 = xl1.drop(columns=['todrop'])

def dropLast(name):
    name = name[:-1]
    return name
xl1['player'] = xl1['player'].apply(dropLast)

xl1['pos'] = 'QB'

xl1['posRank'] = 'NA'
for i in range(len(xl1)):
    team = xl1.iloc[i]['team']
    season = xl1.iloc[i]['season']
    week = xl1.iloc[i]['week']
    player = xl1.iloc[i]['player']
    slicedf = xl1.loc[(xl1['team']==team) & (xl1['season']==season) & (xl1['week']==week)]
    slicedf = slicedf.sort_values(by=['passA'], ascending=False, ignore_index=True)
    posRank = slicedf.index[slicedf['player'] == player].to_list()[0]
    posRank += 1
    posRank = str(posRank)
    xl1.at[i, 'posRank'] = posRank
xl1['posRank'] = xl1['pos'] + xl1['posRank']

In [108]:
# Clean RBs
xl2 = pd.read_csv('data_raw/weekly_rb.csv')

xl2 = xl2.drop(columns=['Unnamed: 0', 'Unnamed: 2_level_0_Pts*'])

xl2 = xl2.rename(columns={'Unnamed: 0_level_0_Player':'player', 'Unnamed: 1_level_0_Game':'opponent',
       'Passing_Att':'passA', 'Passing_Cmp':"passC", 'Passing_Yds':"passY",
       'Passing_TD':'passT', 'Passing_Int':'passI', 'Passing_2Pt':'pass2', 'Rushing_Att':'rushA',
       'Rushing_Yds':'rushY', 'Rushing_TD':'rushT', 'Rushing_2Pt':'rush2', 'Receiving_Rec':'recC',
       'Receiving_Yds':'recY', 'Receiving_TD':'recT', 'Receiving_2Pt':'rec2', 'Fumbles_FL':'fum', 'Fumbles_TD':'fumT'
       })
xl2 = xl2[['player', 'season', 'week', 'team', 'opponent', 'passA', 'passC', 'passY', 'passT', 'passI', 'pass2',
       'rushA', 'rushY', 'rushT', 'rush2', 'recC', 'recY', 'recT', 'rec2',
       'fum']]
xl2[['tm1', 'tm2']] = xl2['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl2['opponent'] = xl2.apply(teamPicker, axis=1)

xl2 = xl2.drop(columns=['tm1', 'tm2'])

xl2[['player', 'todrop']] = xl2['player'].str.split('.\xa0', expand=True)
xl2 = xl2.drop(columns=['todrop'])

def dropLast(name):
    name = name[:-1]
    return name
xl2['player'] = xl2['player'].apply(dropLast)

xl2['pos'] = 'RB'

xl2['posRank'] = 'NA'
for i in range(len(xl2)):
    team = xl2.iloc[i]['team']
    season = xl2.iloc[i]['season']
    week = xl2.iloc[i]['week']
    player = xl2.iloc[i]['player']
    slicedf = xl2.loc[(xl2['team']==team) & (xl2['season']==season) & (xl2['week']==week)]
    slicedf = slicedf.sort_values(by=['rushA'], ascending=False, ignore_index=True)
    posRank = slicedf.index[slicedf['player'] == player].to_list()[0]
    posRank += 1
    posRank = str(posRank)
    xl2.at[i, 'posRank'] = posRank
xl2['posRank'] = xl2['pos'] + xl2['posRank']

In [113]:
# Clean WRs
xl3 = pd.read_csv('data_raw/weekly_wr.csv')

xl3 = xl3.drop(columns=['Unnamed: 0', 'Unnamed: 2_level_0_Pts*'])

xl3 = xl3.rename(columns={'Unnamed: 0_level_0_Player':'player', 'Unnamed: 1_level_0_Game':'opponent',
       'Passing_Att':'passA', 'Passing_Cmp':"passC", 'Passing_Yds':"passY",
       'Passing_TD':'passT', 'Passing_Int':'passI', 'Passing_2Pt':'pass2', 'Rushing_Att':'rushA',
       'Rushing_Yds':'rushY', 'Rushing_TD':'rushT', 'Rushing_2Pt':'rush2', 'Receiving_Rec':'recC',
       'Receiving_Yds':'recY', 'Receiving_TD':'recT', 'Receiving_2Pt':'rec2', 'Fumbles_FL':'fum', 'Fumbles_TD':'fumT'
       })
xl3 = xl3[['player', 'season', 'week', 'team', 'opponent', 'passA', 'passC', 'passY', 'passT', 'passI', 'pass2',
       'rushA', 'rushY', 'rushT', 'rush2', 'recC', 'recY', 'recT', 'rec2',
       'fum']]
xl3[['tm1', 'tm2']] = xl3['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl3['opponent'] = xl3.apply(teamPicker, axis=1)

xl3 = xl3.drop(columns=['tm1', 'tm2'])

xl3[['player', 'todrop']] = xl3['player'].str.split('.\xa0', expand=True)
xl3 = xl3.drop(columns=['todrop'])

def dropLast(name):
    name = name[:-1]
    return name
xl3['player'] = xl3['player'].apply(dropLast)

xl3['pos'] = 'WR'

xl3['posRank'] = 'NA'
for i in range(len(xl3)):
    team = xl3.iloc[i]['team']
    season = xl3.iloc[i]['season']
    week = xl3.iloc[i]['week']
    player = xl3.iloc[i]['player']
    slicedf = xl3.loc[(xl3['team']==team) & (xl3['season']==season) & (xl3['week']==week)]
    slicedf = slicedf.sort_values(by=['recC'], ascending=False, ignore_index=True)
    posRank = slicedf.index[slicedf['player'] == player].to_list()[0]
    posRank += 1
    posRank = str(posRank)
    xl3.at[i, 'posRank'] = posRank
xl3['posRank'] = xl3['pos'] + xl3['posRank']

In [114]:
# Clean TEs
xl4 = pd.read_csv('data_raw/weekly_te.csv')

xl4 = xl4.drop(columns=['Unnamed: 0', 'Unnamed: 2_level_0_Pts*', 'Fumbles_TD'])

xl4 = xl4.rename(columns={'Unnamed: 0_level_0_Player':'player', 'Unnamed: 1_level_0_Game':'opponent',
       'Passing_Att':'passA', 'Passing_Cmp':"passC", 'Passing_Yds':"passY",
       'Passing_TD':'passT', 'Passing_Int':'passI', 'Passing_2Pt':'pass2', 'Rushing_Att':'rushA',
       'Rushing_Yds':'rushY', 'Rushing_TD':'rushT', 'Rushing_2Pt':'rush2', 'Receiving_Rec':'recC',
       'Receiving_Yds':'recY', 'Receiving_TD':'recT', 'Receiving_2Pt':'rec2', 'Fumbles_FL':'fum', 'Fumbles_TD':'fumT'
       })
xl4 = xl4[['player', 'season', 'week', 'team', 'opponent', 'passA', 'passC', 'passY', 'passT', 'passI', 'pass2',
       'rushA', 'rushY', 'rushT', 'rush2', 'recC', 'recY', 'recT', 'rec2',
       'fum']]
xl4[['tm1', 'tm2']] = xl4['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl4['opponent'] = xl4.apply(teamPicker, axis=1)

xl4 = xl4.drop(columns=['tm1', 'tm2'])

xl4[['player', 'todrop']] = xl4['player'].str.split('.\xa0', expand=True)
xl4 = xl4.drop(columns=['todrop'])

def dropLast(name):
    name = name[:-1]
    return name
xl4['player'] = xl4['player'].apply(dropLast)

xl4['pos'] = 'TE'

xl4['posRank'] = 'NA'
for i in range(len(xl4)):
    team = xl4.iloc[i]['team']
    season = xl4.iloc[i]['season']
    week = xl4.iloc[i]['week']
    player = xl4.iloc[i]['player']
    slicedf = xl4.loc[(xl4['team']==team) & (xl4['season']==season) & (xl4['week']==week)]
    slicedf = slicedf.sort_values(by=['recC', 'rushA'], ascending=False, ignore_index=True)
    posRank = slicedf.index[slicedf['player'] == player].to_list()[0]
    posRank += 1
    posRank = str(posRank)
    xl4.at[i, 'posRank'] = posRank
xl4['posRank'] = xl4['pos'] + xl4['posRank']

In [115]:
offense = pd.concat([xl1, xl2, xl3, xl4], axis=0, ignore_index=True)
offense

,player,season,week,team,opponent,passA,passC,passY,passT,passI,...,rushY,rushT,rush2,recC,recY,recT,rec2,fum,pos,posRank
0,Peyton Manning,2010.0,1.0,IND,HOU,57,40,433,3,0,...,0,0,0,0,0,0,0,0,QB,QB1
1,Tom Brady,2010.0,1.0,NE,CIN,35,25,258,3,0,...,0,0,0,0,0,0,0,0,QB,QB1
2,Jay Cutler,2010.0,1.0,CHI,DET,35,23,372,2,1,...,22,0,0,0,0,0,0,1,QB,QB1
3,David Garrard,2010.0,1.0,JAX,DEN,21,16,170,3,0,...,10,0,0,0,0,0,0,0,QB,QB1
4,Carson Palmer,2010.0,1.0,CIN,NE,50,34,345,2,1,...,9,0,0,0,0,0,0,0,QB,QB1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56527,Juwan Johnson,2021.0,17.0,NO,CAR,0,0,0,0,0,...,0,0,0,1,4,0,0,0,TE,TE1
56528,Brevin Jordan,2021.0,17.0,HOU,SF,0,0,0,0,0,...,0,0,0,1,9,0,0,0,TE,TE2
56529,Foster Moreau,2021.0,17.0,LV,IND,0,0,0,0,0,...,0,0,0,1,9,0,0,0,TE,TE1
56530,Albert Okwuegbunam,2021.0,17.0,DEN,LAC,0,0,0,0,0,...,0,0,0,2,5,0,0,0,TE,TE2
56531,Ricky Seals-Jones,2021.0,17.0,WAS,PHI,0,0,0,0,0,...,0,0,0,1,8,0,0,0,TE,TE2

In [137]:
# Clean kickers
xl5 = pd.read_csv('data_raw/weekly_kicker.csv')

xl5 = xl5.drop(columns=['Unnamed: 0', 'Pts*'])

xl5 = xl5.rename(columns={'Player':'player', 'Game':'opponent',
       '50+':'FG50'
       })
xl5 = xl5[['player', 'season', 'week', 'team', 'opponent', 'XPA', 'XPM', 'FGA', 'FGM', 'FG50'
       ]]

xl5[['tm1', 'tm2']] = xl5['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl5['opponent'] = xl5.apply(teamPicker, axis=1)

xl5 = xl5.drop(columns=['tm1', 'tm2'])

xl5[['player', 'todrop']] = xl5['player'].str.split('.\xa0', expand=True)
xl5 = xl5.drop(columns=['todrop'])

def dropLast(name):
    name = name[:-1]
    return name
xl5['player'] = xl5['player'].apply(dropLast)

xl5['pos'] = 'PK'

xl5['posRank'] = 'NA'
for i in range(len(xl5)):
    team = xl5.iloc[i]['team']
    season = xl5.iloc[i]['season']
    week = xl5.iloc[i]['week']
    player = xl5.iloc[i]['player']
    slicedf = xl5.loc[(xl5['team']==team) & (xl5['season']==season) & (xl5['week']==week)]
    slicedf = slicedf.sort_values(by=['FGA', 'XPA'], ascending=False, ignore_index=True)
    posRank = slicedf.index[slicedf['player'] == player].to_list()[0]
    posRank += 1
    posRank = str(posRank)
    xl5.at[i, 'posRank'] = posRank
xl5['posRank'] = xl5['pos'] + xl5['posRank']

In [138]:
# Clean defense
xl6 = pd.read_csv('data_raw/weekly_defense.csv')

xl6 = xl6.drop(columns=['Unnamed: 0', 'Pts*'])

xl6 = xl6.rename(columns={'Team':'player', 'Game':'opponent', 'Sack':'defSack', 'Int':'defI', 'Saf':'defSaf', 'FR':'defFum', 
        'Blk':'defBlk','TD':'defT', 'PA':'defPtsAgainst', 'PassYds':'defPassYAgainst', 'RushYds':'defRushYAgainst', 'TotYds':'defYdsAgainst'
       })
xl6 = xl6[['player', 'season', 'week', 'team', 'opponent', 'defSack', 'defI', 'defSaf', 'defFum', 'defBlk',
       'defT', 'defPtsAgainst', 'defPassYAgainst', 'defRushYAgainst',
       'defYdsAgainst'
       ]]

xl6[['tm1', 'tm2']] = xl6['opponent'].str.split('@', expand=True)

def teamPicker(row):
    team = row['team']
    if row['tm1']==team:
        opp = row['tm2']
    else:
        opp = row['tm1']
    return opp
xl6['opponent'] = xl6.apply(teamPicker, axis=1)

xl6 = xl6.drop(columns=['tm1', 'tm2'])

xl6['pos'] = 'DF'

xl6['posRank'] = 'DF1'

In [139]:
complete = pd.concat([offense, xl5, xl6], axis=0, ignore_index=True)

complete = complete[['season', 'week', 'team', 'player', 
       'pos', 'posRank', 'opponent', 
       'passA', 'passC','passY', 'passT', 'passI', 'pass2', 
       'rushA', 'rushY', 'rushT', 'rush2',
       'recC', 'recY', 'recT', 'rec2', 'fum', 
       'XPA', 'XPM', 'FGA', 'FGM', 'FG50', 
       'defSack', 'defI', 'defSaf', 'defFum', 'defBlk', 'defT', 'defPtsAgainst', 'defPassYAgainst', 'defRushYAgainst', 'defYdsAgainst']]
complete

,player,season,week,team,opponent,passA,passC,passY,passT,passI,...,defSack,defI,defSaf,defFum,defBlk,defT,defPtsAgainst,defPassYAgainst,defRushYAgainst,defYdsAgainst
0,Peyton Manning,2010.0,1.0,IND,HOU,57.0,40.0,433.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Tom Brady,2010.0,1.0,NE,CIN,35.0,25.0,258.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Jay Cutler,2010.0,1.0,CHI,DET,35.0,23.0,372.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,David Garrard,2010.0,1.0,JAX,DEN,21.0,16.0,170.0,3.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Carson Palmer,2010.0,1.0,CIN,NE,50.0,34.0,345.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68744,Miami DolphinsMIA,2021.0,17.0,MIA,TEN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,34.0,110.0,198.0,308.0
68745,Detroit LionsDET,2021.0,17.0,DET,SEA,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,51.0,232.0,265.0,497.0
68746,Denver BroncosDEN,2021.0,17.0,DEN,LAC,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,34.0,237.0,104.0,341.0
68747,Minnesota VikingsMIN,2021.0,17.0,MIN,GB,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,37.0,307.0,174.0,481.0
68748,Cincinnati BengalsCIN,2021.0,17.0,CIN,KC,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,31.0,259.0,155.0,414.0

In [143]:
complete.to_csv('data_raw/allStats.csv')