In [1]:
import pandas as pd

In [2]:
# Read csv
xl_rush = pd.read_csv("data_raw/Game_Logs_Runningback.csv")
xl_rec = pd.read_csv("data_raw/Game_Logs_Wide_Receiver_and_Tight_End.csv")
xl_pass = pd.read_csv("data_raw/Game_Logs_Quarterback.csv")

In [17]:
#Select columns
rush_filtered = xl_rush[['Player Id', 'Year', 'Season', 'Week', 'Opponent',
       'Rushing Attempts', 'Rushing Yards',
       'Rushing TDs', 'Receptions', 'Receiving Yards',
       'Receiving TDs', 'Fumbles'
       ]]
rush_filtered = rush_filtered.rename(columns={'Player Id':'playerID', 'Year':'year', 'Week':'week', 'Opponent':'team', 'Season':'season', 
                'Rushing Attempts':'rushA', 'Rushing TDs':'rushTD', 'Rushing Yards':'rushY',
                'Receptions':'recA', 'Receiving Yards':'recY', 'Receiving TDs':'recTD', 
                'Fumbles':'fumbles'
                })
# Select only regular season
rush_filtered = rush_filtered[rush_filtered['season']=='Regular Season']
rush_filtered.drop(columns='season', inplace=True)
# Clean data
columnList = ['rushA', 'rushTD', 'rushY', 'recA', 'recTD', 'recY', 'fumbles']
for columnName in columnList:
       # Remove null values
       rush_filtered = rush_filtered[~rush_filtered[columnName].str.contains("--")]
       # Clean commas from numbers
       rush_filtered[columnName] = rush_filtered[columnName].str.replace(',', '').astype(int)
rush_filtered.tail(10)

,playerID,year,week,team,rushA,rushY,rushTD,recA,recY,recTD,fumbles
67220,arianfoster/79555,2012,16,MIN,10,15,0,2,14,0,1
67239,arianfoster/79555,2011,12,JAC,22,65,1,7,24,0,2
67241,arianfoster/79555,2011,14,CIN,15,41,0,4,33,0,1
67242,arianfoster/79555,2011,15,CAR,16,109,1,5,58,0,1
67243,arianfoster/79555,2011,16,IND,23,158,1,3,16,0,1
67254,arianfoster/79555,2010,3,DAL,17,106,0,4,20,0,1
67261,arianfoster/79555,2010,11,NYJ,22,84,2,6,59,0,1
67264,arianfoster/79555,2010,14,BAL,20,100,0,4,25,0,1
67277,arianfoster/79555,2009,15,STL,2,7,0,1,13,0,1
67307,dennisgentry/2500786,1991,15,GB,1,17,0,1,8,0,1

In [7]:
rec_filtered = xl_rec[['Player Id', 'Year', 'Season', 'Week', 'Opponent',
       'Rushing Attempts', 'Rushing Yards',
       'Rushing TDs', 'Receptions', 'Receiving Yards',
       'Receiving TDs', 'Fumbles'
       ]]
rec_filtered = rec_filtered.rename(columns={'Player Id':'playerID', 'Year':'year', 'Week':'week', 'Opponent':'team', 'Season':'season', 
                'Rushing Attempts':'rushA', 'Rushing TDs':'rushTD', 'Rushing Yards':'rushY',
                'Receptions':'recA', 'Receiving Yards':'recY', 'Receiving TDs':'recTD', 
                'Fumbles':'fumbles'
                })

In [9]:
pass_filtered = xl_pass[['Player Id', 'Year', 'Season', 'Week', 'Opponent',
       'Rushing Attempts', 'Rushing Yards', 'Rushing TDs', 
       'Passes Attempted', 'Passing Yards', 'TD Passes', 
       'Ints', 'Fumbles'
       ]]
pass_filtered = pass_filtered.rename(columns={'Player Id':'playerID', 'Year':'year', 'Week':'week', 'Opponent':'team', 'Season':'season', 
                'Rushing Attempts':'rushA', 'Rushing TDs':'rushTD', 'Rushing Yards':'rushY',
                'Passes Attempted':'passA', 'Passing Yards':'passY', 'TD Passes':'passTD', 
                'Ints':'ints', 'Fumbles':'fumbles'
                })

In [8]:
xl_pass.columns

Index(['Player Id', 'Name', 'Position', 'Year', 'Season', 'Week', 'Game Date',
       'Home or Away', 'Opponent', 'Outcome', 'Score', 'Games Played',
       'Games Started', 'Passes Completed', 'Passes Attempted',
       'Completion Percentage', 'Passing Yards', 'Passing Yards Per Attempt',
       'TD Passes', 'Ints', 'Sacks', 'Sacked Yards Lost', 'Passer Rating',
       'Rushing Attempts', 'Rushing Yards', 'Yards Per Carry', 'Rushing TDs',
       'Fumbles', 'Fumbles Lost'],
      dtype='object')

In [10]:
pass_filtered

,playerID,year,season,week,team,rushA,rushY,rushTD,passA,passY,passTD,ints,fumbles
0,jaredzabransky/2495791,2007,Preseason,1,CHI,--,--,--,--,--,--,--,--
1,jaredzabransky/2495791,2007,Preseason,2,ARI,--,--,--,4,19,0,0,--
2,jaredzabransky/2495791,2007,Preseason,3,DAL,--,--,--,--,--,--,--,--
3,jaredzabransky/2495791,2007,Preseason,4,TB,2,17,0,22,117,0,1,--
4,billdemory/2512778,1974,Regular Season,1,KC,--,--,--,--,--,--,--,--
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40242,steveramsey/2523725,1971,Regular Season,12,CHI,2,0,0,16,81,0,2,--
40243,steveramsey/2523725,1971,Regular Season,13,SD,--,--,--,25,169,1,3,--
40244,steveramsey/2523725,1971,Regular Season,14,OAK,1,6,0,38,205,1,1,--
40245,steveramsey/2523725,1970,Regular Season,13,SF,--,--,--,--,--,--,--,--
40246,steveramsey/2523725,1970,Regular Season,14,CHI,--,--,--,2,0,0,0,--

In [15]:
rush_filtered['season'].unique()

array(['Preseason', 'Regular Season', 'Postseason', 'Pro Bowl'],
      dtype=object)